// Generates src/data/openings.ts from the Lichess chess-openings TSV files
// (a.tsv … e.tsv, CC0 / public domain — https://github.com/lichess-org/chess-openings).
//
// Each TSV row is `eco \t name \t pgn(SAN with move numbers)`. We replay the SAN
// line with chess.js to recover the UCI move list, then emit ONE compact
// tab/space-delimited string that the runtime parses once at startup. Storing the
// book as a string (not 3.8k object literals) keeps the bundle small.
//
// Run: node scripts/genOpenings.mjs   (re-run to refresh the book — fetches the
// source TSVs from GitHub, so no local data files need to be kept in the repo)
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { Chess } from 'chess.js';

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, '..', 'src', 'data', 'openings.ts');
const BASE = 'https://raw.githubusercontent.com/lichess-org/chess-openings/master';
const FILES = ['a', 'b', 'c', 'd', 'e'];

/** SAN line ("1. e4 e5 2. Nf3 …") → space-joined UCI ("e2e4 e7e5 g1f3"). */
function sanLineToUci(pgn) {
  const chess = new Chess();
  const tokens = pgn
    .replace(/\d+\.(\.\.)?/g, ' ') // strip move numbers "1." / "1..."
    .trim()
    .split(/\s+/)
    .filter(Boolean);
  const uci = [];
  for (const san of tokens) {
    const mv = chess.move(san); // throws on an illegal/unparseable SAN
    uci.push(mv.from + mv.to + (mv.promotion ?? ''));
  }
  return uci.join(' ');
}

const rows = [];
let skipped = 0;
for (const file of FILES) {
  const res = await fetch(`${BASE}/${file}.tsv`);
  if (!res.ok) throw new Error(`Failed to fetch ${file}.tsv: HTTP ${res.status}`);
  const text = await res.text();
  const lines = text.split(/\r?\n/).slice(1); // drop header
  for (const line of lines) {
    if (!line.trim()) continue;
    const [eco, name, pgn] = line.split('\t');
    if (!eco || !name || !pgn) continue;
    try {
      const uci = sanLineToUci(pgn);
      if (uci) rows.push(`${eco}\t${name}\t${uci}`);
    } catch {
      skipped++; // malformed row — skip rather than abort the whole book
    }
  }
}

// Sort by UCI length descending so the longest (most specific) line wins ties;
// the detector already handles this, but sorting keeps diffs deterministic.
rows.sort((a, b) => a.localeCompare(b));

const banner = `// GENERATED by scripts/genOpenings.mjs — do not edit by hand.
// Source: Lichess chess-openings (CC0). Re-run: node scripts/genOpenings.mjs
`;

const body = `${banner}import type { Opening } from '../analysis/openingDetector';

// The full ECO book, encoded as one string: each line is "eco<TAB>name<TAB>uci uci …".
// Parsed once into OPENINGS at module load — keeps the bundle far smaller than
// ${rows.length} object literals would.
const RAW = ${JSON.stringify(rows.join('\n'))};

export const OPENINGS: Opening[] = RAW.split('\\n').map((line) => {
  const [eco, name, uci] = line.split('\\t');
  return { eco, name, uciMoves: uci.split(' ') };
});
`;

writeFileSync(outFile, body);
console.log(`Wrote ${rows.length} openings to ${outFile} (${skipped} skipped).`);
console.log(`Encoded size: ${(body.length / 1024).toFixed(1)} KB`);
